mutation LoginUser($email: String!, $password: String!) {
    loginUser(email: $email, password: $password) {
        token
    }
}

mutation UpdateAccount($email: String!, $firstName: String!, $lastName: String!) {
    updateAccount(email: $email, firstName: $firstName, lastName: $lastName) {
        id
        firstName
        lastName
        email
    }
}