module.exports = [
  '------------------------------------------------------',
  'Let me tell you something.                            ',
  '    There’s no nobility in poverty.                   ',
  '        I’ve been a rich man and I’ve been a poor man.',
  '            And I choose rich every f**king time.     ',
  '                                                      ',
  '                                   – Jordan Belfort.  ',
  '------------------------------------------------------',
  '',
  '',
  '',
  '------------------------------------------------------',
  'CPT IS UNDER DEVELOPMENT AND SHOULD                   ',
  '                ONLY BE USED BY HIGHLY SKILLED MONKEYS',
  '------------------------------------------------------',
  '------------------------------------------------------',
  'CPT IS UNDER DEVELOPMENT AND SHOULD                   ',
  '                ONLY BE USED BY HIGHLY SKILLED MONKEYS',
  '------------------------------------------------------',
];
