mutation CreateStrategy($title: String!, $type: Int!) {
    createStrategy(title: $title, type: $type) {
        id
        title
        description
    }
}
mutation DeleteStrategy($id: ID!) {
    deleteStrategy(id: $id) {
        id
    }
}