mutation CreateStrategy($name: String!, $description: String) {
    createStrategy(name: $name, description: $description) {
        id
        name
        description
    }
}

mutation DeleteStrategy($id: ID!) {
    deleteStrategy(id: $id) {
        id
    }
}