query getStrategiesQuery {
    strategies {
        id
        name
        description
    }
}

query getStrategyQuery($id: ID!) {
  strategy (id: $id) {
    id
    name
    description
    options
    indicators {
      chartPeriod
      type
      signal
      params
      required
      required
    }
  }
}