query GetMyStrategies {
    myStrategies {
        id
        name
        description
    }
}

query GetStrategyById($id: ID!) {
  strategy(id: $id) {
    id
    name
    description
  }
}